version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "php"

[[analyzers]]
name = "javascript"

[[transformers]]
name = "php-cs-fixer"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"